### ISSUE TITLE
runtime exception VERSION 2.65

### ISSUE THREAD

**Issue by bmmm** [pndsn/genetic-car-2#2]
Uncaught TypeError: Cannot read property 'v' of undefined 
cawro.js:1147

**Comment by stephenlb** [comment]
Hi!  We are working on a patch and will release later today.

**Comment by tianon** [comment]
Shouldn't those `cw_*` functions be using `scores.length` instead of `generationSize` to fix this issue?

**Comment by tianon** [comment]
And by `cw_*`, I mean specifically `cw_average` and `cw_eliteaverage`.  If yes, I'd be happy to submit a pull request for it, if that'll help.

**Comment by stephenlb** [comment]
Good point!

**Comment by stephenlb** [comment]
Pull Request would be super deluxe, yes please.

**Comment by danlangford** [comment]
please close this if that merged pull request solved the problem
